### ISSUE TITLE
Choosing plots from the second iteration by HCR to replace no-permisson plots in the first iteration

### ISSUE THREAD

**Issue by lengyelat** [fmsabatini/sPlotOpen_Manuscript#101]
Consider **X** as the set of plots in the first iteration, _x_i_ being a notation for one single plot. Similarly, **Y** is the set of plots in the second iteration, _y_j_ is one of the plots. Imagine that you don't have the permission for _x_i_ plot, so you need to take _y_j_ instead. But how do you select _y_j_ out of **Y**? If you select it randomly, there is high chance that _y_j_ will be similar to a plot with permission in **X**, e.g. _x_k_, but not _x_i_. Therefore, _y_j_ will not be the best to replace _x_i_ and keep the representativity of the subsample.
However, it is not difficult to design a method that selects substitute plots from the reserves.  We simply need to modify the script of HCR in a way that we can set a number of plots in the stratum under resampling to be always selected, and only the rest to be selected randomly. For example, consider a stratum with 70 plots, 50 of them was selected in the first iteration. However, 5 of them have no permission, so we need to selected 5 more out of the rest 20. In the modified HCR in each trial 45 preselected plots with permission are always selected, while 5 ones are randomly drawn from the rest 20. Therefore, in each trial the dissimilarity-based criteria are evaluated for the pre-selected plots and for the randomly selected plots together. The only problem is that the iterations should not be done separately, since we must know how many plots in the first iteration need to be replaced. Maybe it is too late but shall I do the modification for the HCR script?

**Comment by fmsabatini** [comment]
This is a very good point, but clashes with the reality of the negotiation procedure, since we could not afford to make multiple loops of negotiations, depending on the plots being selected or not. We acknowledge ours is a suboptimal compromise, and now mention this inescapable truth at line:
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/30.Methods.md#L13
