### ISSUE TITLE
On plot sizes

### ISSUE THREAD

**Issue by lengyelat** [fmsabatini/sPlotOpen_Manuscript#105]
Probably it is too late to make such fundamental change but let me make a comment on plot sizes.
Plot size strongly influences how we assess beta diversity: with smaller plots we see less overlap between communities than with larger plots. HCR resampling tries to maximize the average dissimilarity in the subsample while keeping the dissimilarities to range within as narrow interval as possible. If you apply HCR on a sample with varying plot size, it is very hard to predict what will happen. If there are many small plots showing high dissimilarity to all other plots, they are more likely selected than larger plots which seem redundant due to lower dissimilarity to the other plots. If there are very few small plots showing high dissimilarity to others, while larger plots are more evenly distributed in the multivariate space, small ones may not be selected in the final subsample because they increase the variance of dissimilarities significantly. Fortunately, this can be counterbalanced to some degree due to the high number of plots selected from each stratum. However, I think it would have been a wise idea to make a stratification according to plot size (e.g 1 to 10 m2, 10 to 100 m2, 100 to 1000 m2...), and apply HCR on different plot sizes separately. This also makes sense from a more practical viewpoint. The decision on plot size is a rather arbitrary one and is dependent on the aims of the study (both in field and when filtering data from a database). For any study, there is an optimal range of plot sizes, and the rest sizes are irrelevant. Thus it would have been straightforward to keep the range of plot sizes throughout the entire range along PCs as broad as possible to help studies with various needs.
I fully accept that this is not possible to change now but the issue might be worth a discussion in the text.

**Comment by fmsabatini** [comment]
jewald472 commented 2 days ago in PR https://github.com/fmsabatini/sPlotOpen_Manuscript/pull/140

>I am concerned about
>the immense range of plot sizes, which contain unreasonably small as well as large "plots" - please list proportions of size classes in Table 2.

**Comment by fmsabatini** [comment]
@jewald472 I did this in commit - https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/2563635767111fa874cdae60c3034e08d75cd04a

**Comment by fmsabatini** [comment]
Very good point on plot size, but there's little we can do a the moment. Personally, I feel opening this point for discussion might backfire. The paper is not really about the method, but about the data. I would wait and see what the referees say about it. I added a note mentioning that in case a different resampling scheme is needed, so that it also includes plot size, this can be done by getting in touch with us:
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/60.TechnicalValidation.md#L26
