### ISSUE TITLE
Internal variation of strata

### ISSUE THREAD

**Issue by lengyelat** [fmsabatini/sPlotOpen_Manuscript#106]
The variation along PCs are very hard to link to real world without reference to any background variable. It would help understanding the procedure and the content of the database if you could add some examples, measures of beta diversity, SD of environmental variables, an ordination diagram, or some kind of description which shows how much variation is contained within a stratum applied in the resampling.

**Comment by fmsabatini** [comment]
I see some links between this issue and Issue https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/58. 
It might make sense to discuss them together.

**Comment by fmsabatini** [comment]
![](https://github.com/fmsabatini/sPlotOpen_Manuscript/blob/master/content/images/pca.panel.png)

**Comment by fmsabatini** [comment]
We discussed the issue with @hbruelheide and @lenjon today. We came to the idea of embedding the figure below to show at least the geographic distribution of plots in a set of PCA grid cell:
![pca panel](https://user-images.githubusercontent.com/51127026/101227090-fba7bb00-3696-11eb-90c0-1ac31cd405ce.png)

The points are selected randomly (I divide the PCA graph in four quadrants and randomly select one pixel with >45 plots in each quadrants). 
Suggestions on how to improve the graph are welcome.

**Comment by lengyelat** [comment]
Thank you, Francesco, I like your idea. It gives at least some insight into both the coverage of individual PCA grid cells and the total sample. It is really nice to see how real gradients are covered in the PCA. I wonder, however, whether the random choice of exemplary cells is the best. Maybe if you choose four neighbour cells with overlapping pairs along the two PCA axes (like a 2x2 table), you could also show the degree of separation between cells. Surely, in this case you must find a single broader vegetation type with which not all people are familiar and you would not be able to illustrate the total variation of the sample. Anyway, Fig. 1 & 2 already represent the total variation nicely, so we should not be concerned of this here. I am not sure which one is better.

**Comment by lenjon** [comment]
Hi Francesco,

Very well done, this is brilliant :) Exactly how I was envisioning it :)

Maybe you could try the suggestion from Attila to sample an additional set
of four neighbouring (2*2) grid cells, thus we have a set of random grid
cell scattered on the PCA space plus a set of 4 clumped grid cells, which
makes a total of 8 sampled grid cells. What do you think?

By the way, shall we also provide the pca3.RData object for free together
with the code you wrote to generate that figure? That would be nice too :)

I also wonder if we could make an additional panel (or standalone figure)
to display the spatial projection of PCA1 and PCA2, just that people have a
sense of the meaning of these two PCA axes. What do you think?

B est,

Jonathan

Jonathan Lenoir
Chargé de Recherche CNRS

Université de Picardie Jules Verne
Ecologie et Dynamiques des Systèmes Anthropisés
UMR 7058 CNRS-UPJV
1 Rue des Louvels
80000 AMIENS
FRANCE

http://www.u-picardie.fr/edysan/_listing-personnel/jonathan-lenoir/
http://scholar.google.com/citations?user=Xx5
<http://scholar.google.com/citations?user=Xx52nH4AAAAJ>2nH4AAAAJ
<http://scholar.google.com/citations?user=Xx52nH4AAAAJ>
http://www.researchgate.net/profile/Jonathan_Lenoir/
http://jonathanlenoir.wordpress.com/

**Comment by fmsabatini** [comment]
Honestly, I don't think is a good idea to add an additional 4 points. The PCA graph is already a bit clogged, and adding 4 additional insets would require a larger panel (taking ~1/2 a page in the printed article). This is a bit too much, given that the focus of the paper should be on the data, rather than on the method.
I'm also unsure of why replacing the 4 randomly selected point with 4 adjacent ones. If the goal is to show that plots in similar conditions (i.e., adjacent grid cells) have scattered geographic distribution, then I don't see how doing so would add anything to the graph. It already shows that clearly. But maybe I'm not getting the point here.

**Comment by lengyelat** [comment]
In the current version it is nice to see that strata from different parts of the PCA scatterplot are distributed far from each other, which makes sense. It is also good that strata seem to have rather narrow ecological content in comparison with the total data set. However, you selected strata which are obviously different from each other in environmental background, so a very different result would indicate a serious mistake in the methodology. My point was that it would be nice to see how within-strata variation is related to between-strata variation, and I think, if you plot them on a geographical map, 2×2 neighbour cells are more suitable to illustrate the minimal separation between strata. I would simply replace the current figures because of the limited space. From a practical viewpoint, now I cannot decide how broad vegetation unit is represented by C. Does it contain all the vegetation types found over the area covered by the red dots, or only a climatically narrower type within that area?

**Comment by lengyelat** [comment]
"I also wonder if we could make an additional panel (or standalone figure)
to display the spatial projection of PCA1 and PCA2, just that people have a
sense of the meaning of these two PCA axes. What do you think?"

I like this idea, PCA1 and PCA2 put on maps would be very informative.

**Comment by fmsabatini** [comment]
https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/120

**Comment by lenjon** [comment]
@lengyelat I think that the actual version of the figure with the four locations widespread across the PC1-PC2 space that @fmsabatini has depicted here is actually perfect.. Indeed it does show very contrasted biomes (strata here) and yet within each of the four selected pixels or strata (within strata variation), the plots are all located in very similar conditions according to the PC1-PC2 space but could be super widespread geographically which is exactly what we were aiming at when running the resampling algorithm. I think it does nicely show how well this resampling approcah works :) For intance, point A corresponds to cold dry desert conditions with high seasonality according to PC1 (from cold and seasonal to hot and stable) and PC2 (from dry to wet). And we can see it works pretty well on the geographical space (cf. steppe vegetation from inner cold dry ontinental regions in Siberia, as far as I can see. For point D, which is the almost other extreme (hot and stable as well as wet conditions), it is displaying, I guess, plots in the subtropical humid regions of the world :) As for C, it is temperate humid conditions and it works too on the geographical space: New Zealand north-western atlantic Europe as well as the north pacific coast of Vancouver in North America. Finally B is displaying temperate dry conditions and all plots are located in eastern Australia, which means that this combinations of bioclimatic + soil conditions is pretty rare on the planet and mostly restricted to eastern Australia. Overall, I think this figure is really amazing and nicely illustrate our work. I really love it as is and I think we should not change it but maybe just better explain the meaning of the PC axes to help the reader interpret that figure correctly (as I tried to do in this thread). Nice work @fmsabatini 👍 

So, I do agree with you @lengyelat that we need to provide (in an appendix) the information necessary for the reader to correctly interpret the meaning of the two PC axes. I think this was also a comment from other co-authors and I remember that @florianjansen also made this comment, right? Hence, when mentioning PC axes in the main text and the caption of figure 2, then we should refer to the appendix displying the spatial distribution of PC1 and PC2 as well as the biplot to interpret PC1 and PC2 correctly. In fact, we should do a better job at explaining the PCA as it is actually part of the engine and the heart of the sampling design we used to resample sPlot.

**Comment by fmsabatini** [comment]
Ok. We now have a biplot in the supplementary material:
https://fmsabatini.github.io/sPlotOpen_Manuscript/#figure-s1
and a panel with the global distribution of PCA values:
https://fmsabatini.github.io/sPlotOpen_Manuscript/#fig:Figure2

I decided to stick to the 4 randomly selected points (which changed a bit since Jonathan made his comment).
