### ISSUE TITLE
Target Journal - Global Ecology and Biogeography?

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#136]
Should we reconsider the target journal and switch from Scientific Data to GEB?

_Originally posted by @lgzrf in https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/24#issuecomment-734310900_
>Thanks Francesco.  I approve the manuscript and have provided some edits.  I would prefer it to be submitted to a different journal (GEB), and have emailed separately with reasons why.  Anyway, it is a very good manuscript that is pretty much ready to submit.  Best wishes, Richard (Field).

**Comment by fmsabatini** [comment]
After the input by @lgzrf, @lenjon @hbruelheide and me discussed whether it wouldn't make more sense to aim at having the paper published in GEB. We believe it does make sense, even if there is a list of pros and cons that could be discussed. 
We are inclined to have the paper submitted to GEB, but we would like to hear from our coauthors whether there are strong arguments against doing so.

**Arguments in favour** as formulated bu @lgzrf 
> 1. The groundwork for acceptance by GEB has already been done:

>a) The data paper that ended up being published in JVS was all but accepted at GEB but then was stopped by the issue of it being against the journal policy to have a data paper without openly accessible data.  That objection does not apply to this new paper!  And I don’t think any ‘novelty’ has been lost by publishing the JVS paper – in fact, it has potentially enhanced this contribution by getting sPlot better known, priming the research community to now be served by the open data release of a large and well-chosen set of plots from sPlot.

>b) I took the liberty to contact Brian McGill to see whether he would welcome such a paper in GEB.  His response was: “I think if there is going to be a full release of the data and it is more than just an incremental update to the last release (which it probably is since the last release was not open access), then GEB would love to have it as a data paper.”  We can legitimately include this feedback in our cover letter as a very positive response to a presubmission enquiry.

>2. GEB is a better and more appropriate journal for this paper than Scientific Data is:

>a) The dataset being released with this paper will in my opinion be a fantastic one for macroecology, and I hope and expect that it will become well used by that community.  The thinning via environmental stratification that Jonathan and others developed is a really good way of producing a dataset that has maximal coverage, is still large, but manageable, and one that suffers minimally from the over-concentration of data in a few small parts of the world.  GEB is the home of macroecology, and this dataset is a major development in macroecology – a gift to the field, really.

>b) GEB is a more prestigious journal than Scientific Data – in my opinion, but also if you go by impact factor and journal history.  Note that GEB’s IF went up in the most recent listings while most other ecology journals’ IFs went down; GEB’s IF is set to increase again next time because the best-cited papers last time round were mostly 2018 ones.  GEB papers are pretty consistently high quality, while Scientific Data is a behemoth that carries a lot of mediocre contributions, as well as a few really well cited ones.

>c) Many in the sPlot community are ‘bought in’ to GEB. As well as myself, other GEB editors on our author list importantly include you Jonathan (of course) and also Franzi Schrodt, Brody Sandel, Brian Enquist and John-Arvid Grytnes (I might also have missed one or two).
>3. Wider considerations and ethics in scientific publishing:

>a) Katrin Bohning-Gaese said, when she regretfully stepped down from being an Associate Editor at the journal because of her major new role at Senckenberg, that GEB really helped macroecology become acceptable in Germany.  Before the journal became influential, apparently it was very difficult to pursue any macroecology in Germany.  The roles that first Rob Whittaker and then David Currie played in this, as consecutive Editors in Chief c. 1990-2015 were crucial, but so was the buy-in from Blackwell (and later Wiley).  I argue that this service to macroecology in Germany and globally is valuable and worth remembering.

>b) In contrast, it is much less clear that Springer Nature is good for our discipline, or science more generally.  Wiley is no angel, of course, and I do quite frequently get frustrated by their approaches, often.  But Springer Nature is in a different league.  You might have seen that Nature itself has just decided that its open access fees will be €9,500 per article! (See https://www.nature.com/articles/d41586-020-03324-y?utm_source=twt_nnc&utm_medium=social&utm_campaign=naturenews).  Think how much research money will be lost to publishing, with such rates, and also the distortions it creates!  Worse, they are proposing to offer half-price publishing for people who pay a non-refundable fee of €2,190 up front, ‘to pay for an editorial assessment and the peer-review process’ (the key part of which is done for free by us!).  I think this is a cynical ploy to ensure that all good papers end up being published by one of the many Springer Nature journals because once Nature rejects the paper, that initial fee then contributes towards the publishing fees for other journals in the stable (such as Scientific Data, where the fee would cover most of the cost), but is lost by the authors if they go to a journal owned by a different publisher (like GEB or virtually all the specialist ecology and biogeography journals).  In other words, if authors think their paper has a chance in a high-ranking Nature journal and pay this fee then their (good) paper will almost certainly end up being published in one of the other Springer Nature journals, such as Scientific Reports or Scientific Data.  It is a serious threat, therefore, to all the other journals, including GEB and JVS and all the society journals that do so much to fund our professional societies, and so on.  So, at least where there is no clear advantage of choosing a Springer Nature journal over a non-Springer Nature one, then I think we should aim to submit to non-Springer Nature ones, if we care at all about our discipline.  As I have tried to argue above, this is such a case – indeed, I think GEB is the better journal for this paper anyway.

**Arguments against:**
1) The paper has been written with Scientific Data in mind, so  it will require a re-edit. This is somewhat a pity, after 100/155 coauthors have already read, edited and approve the ms.

2) Changing after so many coauthors approved submission requires at least some discussion, which can be laboursome given the high number of coauthors

3) sPlot is well known among macroecologists. Even if GEB is, legitimately, the house of most of them, I believe that most macroecologists will track our paper no matter where we publish it. On the other hand, we strive to reach new communities of scientists, so to enlarge the number of people aware of sPlot, and therefore the number of users. I think of geographers or remote sensers, but there might be other groups I can't think of. By publishing in a journal other than GEB, we hope to better intercept these communities. Whether Sci. Data is the right choice is, of course, questionable.


In our opinion, the arguments in favour are stronger than those against, since these can all be (more or less) easily overcome. Yet, we might be overlooking some other important aspects. Suggestions?

**Comment by mhatim99** [comment]
How much time expected this change would take? If this is not going to be too much time consuming, then I would agree to this suggestion.

**Comment by fmsabatini** [comment]
Included the alternative abstract, originally formulated by @lgzrf, and modified to include the latest changes in the original abstract in the manuscript. 
Commit https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/566c67d24a05303f982ffc2f5292b74c10a56648

**Comment by mgsperandii** [comment]
I think GEB would be a great choice. Besides its rising IF, it really is a prestigious journal, which is what counts most in my opinion. Of course there would be additional work to do, but the reward would come from having the paper published where it belongs to..i.e. in the home of macroecology :)

**Comment by juergen-dengler** [comment]
I think that GEB is clearly the better option for all the arguments nicely elaborated by Richard (indeed I was astonished when I orginally heard that you plan to submit to Sci. Data and not to GEB anymore).

**Comment by fmsabatini** [comment]
Not many coauthors expressed an opinion on this matter, but those who did (also via private emails) were all in favour (or at least not against) the idea of switching to GEB. I'm initiating the submission and close this issue now.
Thanks for your insights
