### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by Petr-Petrik** [fmsabatini/sPlotOpen_Manuscript#150]
My organisation declares the need to cite this acknowledgment in publication: "This study was supported by long-term research development project No. RVO 67985939 of the Czech Academy of Sciences.“ Please, include this sentence by my name and my colleague Jiří Doležal (current deputy custodian of Korean Forest Database GIVD ID AS-00-001) instead of the acknowledgement to the project that has nothing to do with this dataset (https://starfos.tacr.cz/cs/project/LTAUSA18007). We have built Korean Forest Database since 2010 with support of many projects that are over. Thank you!

**Comment by fmsabatini** [comment]
Thanks Petr, 
done here:
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/70.Acknowledgements_et_al.md#L29
