### ISSUE TITLE
CWM formula

### ISSUE THREAD

**Issue by mafla** [fmsabatini/sPlotOpen_Manuscript#157]
Why do we need to count the species for each plot only?https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/fe2931d01c29c1ea7bc70cabf8e3b0e590b1f14e/content/03.Methods.md#L59

should we just count from 1 to n, where n the global number of species? Reason: If p~i would then be simply 0 when a species is not present at a plot. WOuld be a bit more elegant to my mind.

**Comment by fmsabatini** [comment]
True. But, I think the formula will be more familiar to our readers if we keep mentioning plots.
