### ISSUE TITLE
Manuscript title

### ISSUE THREAD

**Issue by lenjon** [fmsabatini/sPlotOpen_Manuscript#160]
I did not find where to edit the ms title and thus I decided to create a new issue. The name of the database in the current title is written "sPlot open" instead of "sPlotOpen". Could you please update that @fmsabatini so that it is harmonized throughout the ms? Also could you update the dash afyter sPlotOpen so that it is a long dash "–" instead of a short dash "-" symbol? So, in the end the title should read "sPlotOpen – An environmentally-balanced, open-access, global dataset of vegetation plots

**Comment by fmsabatini** [comment]
Yep, I also noticed that earlier today. It's fixed now.. and I'm about to add the long dash

**Comment by fmsabatini** [comment]
Done in commit https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/87dccc4e9e3fcfd6a60beced92eb5ccbbf07b4b0
