### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by lenjon** [fmsabatini/sPlotOpen_Manuscript#162]
Same for figures, I did not find where to edit the captions and thus I am openning a new issue on figures. For figure 1, in the caption, you do not mention the panels explicitly (cf. a and b) while you did name the two panels (a) and (b). Thus, my question is whether we should replace "Top" and "Bottom" by (a) and (b) in the caption or simply remove the (a) and (b) symboles in the figure itself. Also could you replace:

"Spatial distribution of vegetation plot density in the first resampling iteration (n = 49,787)." 

By:

"Spatial distribution of vegetation plot density for the environmentally-balanced dataset selected by the first resampling iteration (n = 49,787)."

I think it is very important to mention in the caption the keyword "environmentally-balanced dataset" when referring to the first resampling iteration because that is the dataset we should encourage users to use, not the large one which is not perfectly balanced in the end.

**Comment by lenjon** [comment]
About figure 2, and contrary to figure 1, you do not provide panel IDs such as (a), (b) and (c). I think that we should harmonize that across the three figures. Either we use "Top", "Bottom", etc. in teh caption and thus we do not provide panel IDs like (a), (b), etc. or we do provide clear panel IDs (a, b, c, etc.) that we explicitly mention in the figure captions instead of using "Top", "Bottom", etc.

**Comment by fmsabatini** [comment]
Thanks, all fixed in commit https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/4c590b033e1ab635d7e28da0cb1a5367a4862ecf
I deleted the letter to indicate subfigures in panels (for the simple reason that it'd be super messy, otherwise, in figure 2). In case the journal asks us to add these letters, we'll figure out a way
