### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#17]
We need to choose a license, or a set of licenses for:
1) Dataset itself,
2) Code used to produce the dataset (https://github.com/fmsabatini/sPlotOpen_Code/)
3) Code used to produce the manuscript (i.e., fmsabatini:sPlotOpen_Manuscript)

https://choosealicense.com/licenses/
https://creativecommons.org/choose/
https://choosealicense.com/

**Comment by lenjon** [comment]
Isn't it creative commons the best in our case? I must say that I have no experience with licenses...

**Comment by fmsabatini** [comment]
It depends on the repository we will choose. It will be, probably, iData Portal. In any cases, CC-BY could be our first choice
