### ISSUE TITLE
Opt-in or Opt-out paper?

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#2]
Should this be an opt-in or opt-out paper?

**Comment by lenjon** [comment]
Sorry, I cannot recall the difference between the two ;) Could you briefly re-explain it to me?

**Comment by lenjon** [comment]
Is opt-out the case in which everyone is included as a co-author by default and excluded if and only if the person directly request to be excluded from the co-author list? If yes, maybe the opt-in case is better: we invite and include only those who specifically ask for it...

**Comment by fmsabatini** [comment]
Opt-in, then
