### ISSUE TITLE
Approve Submission

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#24]
Please let us know if you approve submission, by leaving a message in this issue. I will then tick the box. 
New Updated list
 - [x] Aaron Pérez-Haase
 - [x] Abel Monteagudo Mendoza
 - [x] Adrian Indreica
 - [x] Alexander Christian Vibrans
 - [x] Alicia Acosta
 - [x] Ali Kavgacı
 - [x] Alireza Naqinezhad
 - [x] Alvaro G. Gutierrez
 - [x] Andraž Carni
 - [x] André Luis de Gasper
 - [x] Andrey Korolyuk
 - [x] Aníbal Pauchard
 ~~- [ ] Anita Smyth~~ opted out
 - [x] Anke Jentsch
 - [x] Anna Kuzemko
 - [x] Anne D. Bjorkman
 - [x] Antonio Galán-de-Mera
 - [x] Arindam Banerjee
 - [x] Arkadiusz Nowak
 - [x] Attila Lengyel
 - [x] Aurora Levesley
 - [x] Ben Sparrow
 - [x] Birgit Jedrzejek
 - [x] Borja Jiménez-Alfaro
 - [x] Brian Enquist
 - [x] Brody Sandel
 - [x] Bruno Herault
 - [x] Cindy Q. Tang
 - [x] Corrado Marcenò
 - [x] Cyrille Violle
 - [x] Cyrus Samimi
 - [x] Debora Vanessa Ligner
 ~~- [ ] Desalegn Wana~~ opted out
 - [x] Dirk Nikolaus Karger
 - [x] Donald A. Walker
 - [x] Donald Waller
 - [x] Eduardo Vélez-Martin
 - [x] Elise Arnst
 - [x] Elizabeth Kearsley
 - [x] Els De Bie
 - [x] Emiliano Agrillo
 - [x] Emmanuel Garbolino
 - [x] Erwin Bergmeier
 - [x] Eszter Ruprecht
 - [x] Fabio Attorre
 - [x] Fahmida Sultana
 - [x] Farideh Fazayeli
 - [x] Flavia Landucci
 - [x] Florian Jansen
 - [x] Francesco Maria Sabatini
 - [x] Franziska Schrodt
 - [x] Frederic Lens
 - [x] Gerhard E. Overbeck
 - [x] Gianmaria Bonari
 - [x] Gonzalo Rivas-Torres
 - [x] Gregory Richard Guerin
 - [x] Guillermo Hinojos Mendoza
 - [x] Gwendolyn Peyre
 - [x] Hamid Gholizadeh
 - [x] Helge Bruelheide
 - [x] Henrik von Wehrden
 - [x] Hjalmar Kühl
 - [x] Holger Kreft
 - [x] Hongyan Liu
 - [x] Hua-Feng Wang
 - [x] Hanhuai Shan
 - [x] Idoia Biurrun
 - [x] Inger Greve Alsos
 - [x] Ioannis Tsiripidis
 - [x] Isabelle Aubin
 - [x] Iva Apostolova
 - [x] Jalil Noroozi
 - [x] János Csiky
 - [x] Jens-Christian Svenning
 - [x] Jens Kattge
 - [x] Jérôme Munzinger
 - [x] Jesper Erenskjold Moeslund
 - [x] Jiri Dolezal
 - [x] John-Arvid Grytnes
 - [x] John Janssen
 - [x] John S. Rodwell
 - [x] Jonas V. Müller
 - [x] Jonathan Lenoir
 - [x] Jörg Brunet
 - [x] Jörg Ewald
 - [x] Josep Penuela
 - [x] Jozef Šibík
 - [x] Jürgen Dengler
 - [x] Jürgen Homeier
 - [x] Jutta Kapfer
 - [x] Karsten Wesche
 - [x] Kim André Vanselow
~~- [ ] Kim Sarah Jacobsen~~ suggested alternative coauthor
 - [x] Kiril Vassilev
 - [x] Ladislav Mucina
 - [x] Larisa Khanina
 - [x] Laura Casella
 - [x] Luis Cayuela
 - [x] Luzmilla Arroyo
 - [x] Manfred Finckh
 - [x] Marco Schmidt
 - [x] Marijn Bauters
 - [x] Marta Gaia Sperandii
~~- [ ] Marten Winter~~ refrains from being coauthor
 - [x] Martin Zobel
 - [x] Meelis Pärtel
 - [x] Melisa Giorgis
 - [x] Michael Kessler
 - [x] Michele De Sanctis
 - [x] Miguel Alvarez
 - [x] Miguel D. Mahecha
 - [x] Milan Chytrý
~~- [ ] Milan Valachovič~~ Opted-out
 - [x] Mohamed Abd El-Rouf Mousa El-Sheikh
 - [x] Mohamed Z. Hatim
 - [x] Mohammed A.S. Arfin Khan
 - [x] Norbert Hölzel
 - [x] Norbert Jürgens
 - [x] Oliver L. Phillips
 - [x] Oliver Purschke
 - [x] Panayotis Dimopoulos
 - [x] Patrice De Ruffray
 - [x] Pavel Shirokikh
 - [x] Petr Petřík
 - [x] Petr Sklenář
 - [x] Rasmus Revermann
 - [x] Renata Ćušterevska
 - [x] Richard Field
 - [x] Risto Virtanen
 - [x] Robert K. Peet
 - [x] Roberto Venanzoni
 - [x] Rodlfo Vásquez Martínez
 - [x] Sergey Yamalov
 - [x] Sophie Gachet
 - [x] Solvita Rūsiņa
 - [x] Stephan M. Hennekens
 - [x] Susan Wiser
 - [x] Svetlana Aćić
 - [x] Sylvia Haider
 - [x] Tarek Hattab
 - [x] Tatiana Lysenko
 - [x] Tetiana Dziuba
 - [x] Thomas Wohlgemuth
 - [x] Timothy Whitfeld
 - [x] Timothy Killeen
 - [x] Tomáš Černý
 - [x] Tomáš Peterka
 - [x] Tsipe Aavik
 - [x] Urban Šilc
 - [x] Ute Jandt
 - [x] Vadim Prokhorov
 - [x] Valentin Golub
 - [x] Valerijus Rašomavičius
 - [x] Valério De Patta Pillar
 - [x] Vasiliy Martinenko
 - [x] Victor Chepinoga
 - [x] Viktoria Bondareva
 - [x] Viktoria Wagner
 - [x] Viktor Onyshchenko
 - [x] Wannes Hubau
 - [x] Wolfgang Willner
 - [x] Yves Bergeron
 - [x] Željko Škvorc
 - [x] Zhiyao Tang
 - [x] Zvjezdana Stančić
 - [x] Zygmunt Kącki

**Comment by Alectoria** [comment]
Hi Francesco, thanks for the invitation. I approve but was unable to tick the box.

**Comment by micheledesanctis** [comment]
Same thing happened to me: it is not possible to tick the box. However, thank you very much for the invitation and I approve the submission

**Comment by marcoschmidtffm** [comment]
Same for me. I approve. Cheers, Marco

**Comment by bsandel** [comment]
Me too! I've made some comments on the first three sections (hopefully correctly!), and I will look through the rest soon. Best, Brody

**Comment by HVW12** [comment]
Greetings! Many thanks for the fantastic work, I approve, and I am glad to be included. Cheers, Henrik

**Comment by ValerijusRasomavicius** [comment]
Hi, thanks for invitation. I approve. Valerijus

**Comment by vadimprokhorov** [comment]
Hello, many thanks for the great work. I approve, Cheers, Vadim.

**Comment by juergen-dengler** [comment]
Hi Francesco, I approve, but your check box is not working

**Comment by fmsabatini** [comment]
> Please let us know if you approve submission, by leaving a message in this issue. I will then tick the box.

That's why I asked to leave a message :-)

**Comment by ValerijusRasomavicius** [comment]
Yes, I approve submission. Sorry for the misunderstanding the first time.

Best regards,
Valerijus Rašomavičius

**Comment by mhatim99** [comment]
Hi Francesco,
The manuscript is excellent, indeed. Thanks for accepting my edits and for your efforts. I approve the submission.
Best wishes,
Zakaria

**Comment by Idoia-gif** [comment]
Hi Francesco, I approve submission. Thank you very much, Idoia

**Comment by skvorc** [comment]
Hi Francesco, thanks for the invitation. I approve. Best regards, Željko

**Comment by mgiorgis2020** [comment]
Hi Francesco, I approve submission. Cheers, Melisa

**Comment by AnibalPauchard** [comment]
Hi Francesco,
If possible add my second affiliation "Institute of Ecology and Biodiversity (IEB), Chile"
I approve the submission, thanks so much for your efforts!
Aníbal Pauchard

**Comment by lenjon** [comment]
Hi Francesco,

Of course, as you may expect ;) I also approve the submission 👍 

Best,

Jonathan

**Comment by fmsabatini** [comment]
Dear @AnibalPauchard (and whomever want to update her\his contact and affiliation information)
Please fill in this google form (and drop me a line) as documented in the issue https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/4
https://docs.google.com/forms/d/e/1FAIpQLScMP85xd9OERFHyHJXlvCOjbmcGQEPcqT2YCcYmU49iX-HfUQ/viewform
I will use the info to **replace** the previous information, so please, make sure it is complete. The form allows to insert up to 3 affiliations

**Comment by TarekHattab** [comment]
Hi Francesco, thanks for the great work. I approve  the submission but was unable to tick the box.

Best, 

Tarek

**Comment by AnibalPauchard** [comment]
Thanks Francesco, my affiliations are now updated.
------------------------------------------------
Aníbal Pauchard
Laboratorio de Invasiones Biológicas (LIB) www.lib.udec.cl
Facultad de Ciencias Forestales
Universidad de Concepción
Casilla 160-C, Concepción, Chile
Fonos: 56-41-2204934, 2204679
pauchard@udec.cl, anpauch@gmail.com

**Comment by fmsabatini** [comment]
Robert Peet approved per mail today

**Comment by JonasM-WA** [comment]
Hi Francesco, thank you for the invitation. Just to confirm that I approve the submission.

Jonas

**Comment by AntonioGalan2020** [comment]
Hi Francesco,
Thank you for the invitation to the paper. I approve the submission, but I coudn't tick the box.
Cordially, Antonio Galán de Mera

**Comment by Viktor-Onyshchenko** [comment]
I approve.
Viktor Onyshchenko

**Comment by GianmariaBonari** [comment]
Ciao Francesco,

Thanks for your work. I approve.

Cheers,
Gianmaria

**Comment by fmsabatini** [comment]
Hua-Feng Wand approved by email

**Comment by BrunoHerault** [comment]
Dear Francesco. I approve the submission. best, Bruno

**Comment by florianjansen** [comment]
I approve the submission.
Best
Florian

**Comment by jiriddolezal** [comment]
Dear Francesca, thanks for great work, I approve, and I am glad to be included. Cheers, Jiri Dolezal

**Comment by marijn-bauters** [comment]
Dear Francesco,
I approve the submission.
all the best
marijn

**Comment by eszterruprecht** [comment]
Dear Francesco, thanks for the invitation. I approve the submission. All the best, Eszter

**Comment by kamapu** [comment]
Hello, Francesco, I'm also approving the submission. Greetings and congrats!

**Comment by MichaelKessler979** [comment]
I approve submission. Paper looks great and I am happy to have sPlots at least partly with Open access! Michael Kessler

**Comment by fmsabatini** [comment]
Wolfgang Willner approved by email

**Comment by fmsabatini** [comment]
Yves Bergeron approved by email

**Comment by rvirtane** [comment]
Dear Francesco et al., thanks a lot for advances -  I approve the submission. Best, Risto Virtanen

**Comment by milanchytry** [comment]
I approve! Thank you, and best regards. Milan Chytrý

**Comment by rasrev** [comment]
Hi Francesco,
thanks for all the effort you put into this, good work! approved!
cheers,
Rasmus

**Comment by egarbolino** [comment]
I approve. Thank you very much. Best wishes !
Emmanuel

**Comment by Munzinger-svg** [comment]
Hi, thanks for invitation. I approve. Jérôme

**Comment by Borjez** [comment]
Excellent work Francesco, Jonathan, and Helge! 
I approve.
Borja

**Comment by peterkatomas** [comment]
Dear Francesco,
I approve.
Kind regards, Tomáš Peterka

**Comment by isabelleaubin** [comment]
Thanks for the invitation.
Excellent work! I approve.
Isabelle Aubin

**Comment by Idoia-gif** [comment]
Dear Franceso,
I approve,

Idoia

**Comment by Rusina-S** [comment]
I approve the submission. Many thanks for invitation!
Solvita Rūsiņa

**Comment by rockdazzie** [comment]
Dear Francesco,
I approve the submission. Thank you for this excellent manuscript and for inviting me.
All the best, Kim

**Comment by fmsabatini** [comment]
https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/91
Alicia Acosta approved

**Comment by aacosta-GitHub** [comment]
Dear Francesco, I approve the submission. Thanks for your invitation. 
I've just changed my affiliation and name. Thanks again. Alicia

**Comment by nobelarfin** [comment]
Dear Francesco, Thanks for your Invitation. Excellent manuscript. I approve the submission.
Thanks again. Mohammed A.S. Arfin Khan

**Comment by Fahmida-SUST** [comment]
Dear Francesco Maria Sabatini,
I approve the submission. Thank you for the invitation, excellent manuscript.

Regards,
Fahmida Sultana

**Comment by tomcerny** [comment]
Dear Francesco & Co.,
I am happy to be included in this perfectly cooked work! 
Selected co-editing process on GitHub is a very new for me, but I found this new "universe" really amazing!
Many thanks, Good Luck and firm health!
Tomáš Černý

**Comment by adrianindreica** [comment]
Dear Francesco,
Thank you for the invitation. I approve the submission.
Kind regards. Adrian Indreica

**Comment by Greforb** [comment]
Hi Francesco
Thanks a lot for all your efforts in getting this one ready! It's a fantastic job and I'm sure it will be of use for many biodiversity researchers in the future. I approve its submission.
Jesper Erenskjold Moeslund

**Comment by jhomeier** [comment]
Hi Francesco, 
I approve submission.  Thank you, and best regards,
 Jürgen Homeier

**Comment by aaronperezhaase** [comment]
Hi Francesco,
I approve submission.
Aaron Pérez-Haase

**Comment by fmsabatini** [comment]
https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/94

**Comment by fmsabatini** [comment]
Cyrus Salamini approved by email

**Comment by urbansilc** [comment]
Hi Francesco,
I approve submission.
All the best, Urban Šilc

**Comment by Carni-Andraz** [comment]
Francesco, I approve submission! Nice paper, congratulations to the core team. Could you add my second address (if possible), as University of Nova Gorica, School for viticulture and enology, Vipavska 13, 5000 Nova Gorica. With best wishes, Andraž Čarni

**Comment by fmsabatini** [comment]
@Carni-Andraz done!
Patrice De Ruffray approved by email

**Comment by fisw10** [comment]
Hi Francesco, thank you for the kind reminder! The manuscript looks great and I'm more than happy to approve. Thank you for leading this huge effort!

**Comment by Pavel-Shirokikh** [comment]
Dear Francesco
I approve the submission. Thank you for the invitation. 
Kind regards.

**Comment by GregGuerin** [comment]
I approve submission.

Greg Guerin

**Comment by ekearsle** [comment]
Hi Francesco, I also approve submission. Nice work! Elizabeth Kearsley

**Comment by utejandt** [comment]
Dear Francesco, thank you. I approve the submission. I will send you a few minor edits as notes in the pdf by mail.
Kind regards,
Ute

**Comment by fredericlens** [comment]
Hi Francesco, thanks for the invitation. I approve. Best regards, Frederic Lens

**Comment by annakuzemko** [comment]
Thank you Francesco! Great job! You have my approval! Kind regards, Anna

**Comment by SylviaHaider** [comment]
Hi Francesco, I approve the manuscript. Thanks a lot and congrats to the nice paper! Sylvia

**Comment by fmsabatini** [comment]
Josep Penuelas approved by email

**Comment by CorradoMarceno** [comment]
Dear Francesco 
I wrote my comments some week ago. I hope did you visualized them, for me, it was the first time using GitHub.
I did not know to have to approve the submission, sorry. I approve the submission.
Thank you again for your effort in preparing this nice paper 
Best wishes
Corrado

**Comment by jkattge** [comment]
Hi Francesco, 
Many thanks for sending the reminder. 
I approve.
Cheers,
Jens

**Comment by ghinojos** [comment]
Hi Francesco,
 Thank you for sending the reminder.
I approve.
Cheers,
Guillermo,

**Comment by luiscayuela** [comment]
Hi Francesco,
thanks for the reminder. I approve to be listed as a co-author.
Best,

Luis

**Comment by mgsperandii** [comment]
Hi Francesco :) 
Sorry for the delay, full approval from my side.
Besides, congratulations for the brilliant job: the ms. reads pleasantly (and I do love the Fig. 2 plot)!
Cheers,

Marta

**Comment by fmsabatini** [comment]
Melisa Giorgis and Manfred Finckh approve per email

**Comment by pmeelis** [comment]
I approve. Best, Meelis Pärtel

**Comment by jsibik** [comment]
Thank You, Francesco. I approve this submission, great work regarding sPlot by all of you.

**Comment by tsipeaavik** [comment]
Thanks, Francesco! I approve the manuscript. Kind regards, Tsipe Aavik

**Comment by lgzrf** [comment]
Thanks Francesco.  I approve the manuscript and have provided some edits.  I would prefer it to be submitted to a different journal (GEB), and have emailed separately with reasons why.  Anyway, it is a very good manuscript that is pretty much ready to submit.  Best wishes, Richard (Field).

**Comment by TatianaLysenko** [comment]
Thanks Francesco. I approve the submission.
With best wishes
Tatiana Lysenko

**Comment by HolgerKreft** [comment]
Thanks Francesco. I am happy with being listed as co-author and approve this ms. Best, Holger Kreft

**Comment by JCSvenning** [comment]
Thanks Fransceso - also happy to be listed as co-author and approve the manuscript. Best wishes, Jens

**Comment by anke-jentsch** [comment]
Dear Francesco - I am very grateful and delighted and happy to be a co-author of this manuscript!
Cheers, Anke Jentsch

**Comment by auroralevesley** [comment]
Dear Francesco. I approve the submission and am delighted to be co-author. Great work!
Best wishes
Aurora

**Comment by Idoia-gif** [comment]
DEar Francesco,

I can see that many people is now approving co-authorship.  I think I  
did it, but just in case, here my approval :)

Idoia

**Comment by cviolle** [comment]
Dear Francesco,

I approve, too.

Thanks a lot.
Cyrille Violle

**Comment by wiser-susan** [comment]
I approve.

**Comment by whubau** [comment]
Dear Francesco, I approve, thanks for all the effort!
cheers,
Wannes Hubau

**Comment by fmsabatini** [comment]
Joerg Brunet approved by email

**Comment by acvibrans** [comment]
Dear Sabatini and all; thanks for being part of this group. I approve submission.

**Comment by algasper** [comment]
I approve submission

**Comment by Cindy66120** [comment]
Dear Francesco, I approve the submission.  Thanks for your wonderful writing!

Cindy

**Comment by FlaLanducci** [comment]
Hello Francesco,
I finally found time to read the paper. I found it well done. I approve it for submission.

**Comment by ElsDeBie** [comment]
Hi Francesco, thanks for the great work!
I approve the submission (I have send an update for the affiliation by the google form).
Best regards, 
Els De Bie

**Comment by arnste** [comment]
I approve submission. Thanks to all involved.

**Comment by Petr-Petrik** [comment]
Dear Francesco, 
Thank you for inviting to co-authorship of this great manuscript and I aprove the submission. 
Best, 
Petr

**Comment by fmsabatini** [comment]
Mohamed Abd El-Rouf Mousa El-Sheikh
Joerg Ewald 
Hongyan Liu
Panayotis Dimopoulos
Zhiyao Tang
Andrey Korolyuk
Ali Kavgacı
Inger Greves Alsos
Ioannis Tsiripidis
Panayotis Dimopoulos
confirmed by email

**Comment by valeriopillar** [comment]
Dear Francesco, I approve the submission.
Best,
Valério Pillar

**Comment by fmsabatini** [comment]
Alvaro Gutiérrez approved by email

**Comment by debbyz** [comment]
Dear Francesco, I’m happy to be listed as co-author and approve the manuscript. Thanks for your efforts! Best, Débora

**Comment by fmsabatini** [comment]
Jutta Kapfer
Fabio Attorre
Jalil Noroozi approved per email

**Comment by greenmind1980** [comment]
I approve the manuscript

**Comment by velezedu** [comment]
Dear Francesco, 

Approved! Thanks for the invitation as co-author.

All the best
Eduardo Vélez-Martin

**Comment by benquist** [comment]
Approved. This is an impressive and important contribution. Thank you for the invitation to the sPlot manuscript. 

Sincerely, 
Brian

**Comment by V821-stack** [comment]
Dear Francesco,

Approved! Thanks for the invitation as a co-author sPlot.

All the best.
Victoria Bondareva.

**Comment by SYamalov** [comment]
I approve submission

**Comment by fmsabatini** [comment]
John Janssen 
Gerard Overbeck approved by email

**Comment by mafla** [comment]
Dear Francesco, I approve the submission! Miguel Mahecha

**Comment by fmsabatini** [comment]
Sophie Gachet & Hjalmar Kuehl approved by email

**Comment by lenjon** [comment]
Donald A. Walker recently approved by email --> 100% 👍
