### ISSUE TITLE
Column names in header

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#3]
@lenjon suggested to standardize the column names of the 'header' file.
I copy paste his comment:
We need to be consistent in the way we name the variables in each column. We need to pick a convention for separators when naming variables and stick to it. I would vote for using the underscore symbol "_" as a separator instead of a dot "."

**Comment by fmsabatini** [comment]
Makes a lot of sense to me, since the column names are a bit of a mess with special characters, empty spaces and so so. 
Yet, these names match with those described in [Bruelheide et al. 2019](https://onlinelibrary.wiley.com/doi/10.1111/jvs.12710), S10 if I'm not wrong.
We should be aware that by changing them, we might create confusion.

**Comment by lenjon** [comment]
Indeed, but I think that changing the names here is necessary as we want to make the data available and thus I would make sure to provide a data table of which the header names are easy to understand and for which we have a consistent format that is compatible with data analyses in many softwares like R. Most important is to avoid special characters and pick a convention for separators. My prefer convention is "_" as s separator between words.

**Comment by hbruelheide** [comment]
I agree with Jonathan. Let's switch all column names to underscore.

**Comment by fmsabatini** [comment]
Done. All column names in the header, DT, and CWM files follow now the convention:
Xxxxxx_xxxxx
