### ISSUE TITLE
How to fill-in or change affiliation information

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#4]
There are some coauthors for which I don't have contact information. They should be tracked down, and the information stored in the consortium contact file.
Also, this could be a good occasion for updating all other affiliations, since I expect quite a bit of changes happened in the last two years

**Comment by fmsabatini** [comment]
I set up a google form to collect affiliation information. All coauthors without affiliation or who need their affiliation to be changed, please fill in the form at:

https://docs.google.com/forms/d/e/1FAIpQLScMP85xd9OERFHyHJXlvCOjbmcGQEPcqT2YCcYmU49iX-HfUQ/viewform

**Comment by mhatim99** [comment]
Hi Francesco,
I've filled in the form 3 days ago to edit my affiliation, but I see no change in the metadata.yaml file. I'm not sure if the change showed up to you in the google form, that's why I'm writing this comment.
Thank you in advance,
Zakaria

**Comment by fmsabatini** [comment]
Just a matter of time Zakaria. I still have to import the new affiliations into the pipeline, and I'm waiting for some more coauthors to fill it up, before doing that

**Comment by fmsabatini** [comment]
Done

**Comment by mhatim99** [comment]
> Done

Many thanks, Francesco
