### ISSUE TITLE
How to explain edits in documents

### ISSUE THREAD

**Issue by florianjansen** [fmsabatini/sPlotOpen_Manuscript#49]
How should we comment on our edits?

if it is only a single edit, we can do that of course in the committ message. However in longer paragraphs with multiple edits this becomes unreadable, I guess.

I propose to use invisible markdown comments directly behind the sentences we edited:
They are written as
 \

**Comment by fmsabatini** [comment]
Thanks Florian!
Thanks a very good idea. I'll implement this suggestion in the tutorial document

**Comment by fmsabatini** [comment]
It's now in the Wiki
