### ISSUE TITLE
Exclude Lichens and mosses?

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#5]
Most of the entries are for vascular plants. A small minority of plots also have information on lichen and mosses (a few even for Algae). Should we exclude these taxonomic groups altogether?

**Comment by lenjon** [comment]
I am tempted to exclude these taxonomic groups from the sPlotOpen dataset so that the focus is clearly on vascular plants only.

**Comment by hbruelheide** [comment]
Yes, please let us exclude cryptogams. It does not make sense and they do not have traits (or should not, but with gap-filling they have even stem tissue density...).

**Comment by fmsabatini** [comment]
Done. There is a few hundred taxa which are not classified in taxonomic groups. They are mostly entries at the family level, or entries for which we found no match during the construction of the backbone. I left them in the DT2 table, since some of them are genuine entries.
