### ISSUE TITLE
Figure 2

### ISSUE THREAD

**Issue by TarekHattab** [fmsabatini/sPlotOpen_Manuscript#56]
I wonder if there is no problem in figure 2. There are several vegetation plots which does not match with Whittaker biomes (for example plots in temperature of 5 ° C and a precipitation greater than 200 cm) .Maybe it should be explained somewhere why some combination of temperature and precipitation does not fit into the  Whittaker bioregionalization?

**Comment by fmsabatini** [comment]
It's currently under discussion in the issue https://github.com/fmsabatini/sPlotOpen_Manuscript/issues/50
