### ISSUE TITLE
On Methods

### ISSUE THREAD

**Issue by JCSvenning** [fmsabatini/sPlotOpen_Manuscript#58]
Just a question regarding the plot subsampling procedure per cell in PC1-PC2 space: "More precisely, for a given PC1-PC2 grid cell containing more than 50 vegetation plots, we generated 1,000 random selections of 50 vegetation plots and ranked them according to the mean (ascending order) and variance (descending order) value. Ranks from both sortings were summed for each random selection, and the random selection with the lowest summed rank was considered the most representative of the focal grid cell." Given that a given PC1-PC2 cell may have plots from multiple biogeographic regions (eg the various Mediterranean climate regions around the world) would this procedure not favor selecting all plots from a given region (e.g., Southern Europe), promoting over-representation of certain geographic regions (e.g., Europe)?

**Comment by fmsabatini** [comment]
@lenjon might be more precise here.
My take is that, what you say would be correct if the selection of plots was purely random. However, the Heterogeneity-Constrained Resampling (HCR) algorithm also takes into account species composition:

>  For those grid cells with more than 50 vegetation plots (n = 858), we randomly selected up to 50 vegetation plots using the heterogeneity-constrained random resampling algorithm from Lengyel et al. (2011) [37]. This approach optimizes the selection of a random subset of vegetation plots that encompasses the highest variability in species composition while avoiding peculiar and rare communities, which may represent outliers. We based the quantification of variability in plant species composition among the 50 randomly selected vegetation plots by computing the mean and the variance of the Jaccard’s dissimilarity index (38) between all possible pairs of vegetation plots for a given random selection of 50 vegetation plots (n = 1225)

This means that, in case of plots with identical climatic\soil conditions from different continents, the algorithm will avoid a redundant selection of (+/- similar) plots from the same continent, but rather include as much diversity as possible, i.e., plot from all continents represented, as long as the species composition is sufficiently dissimilar.

**Comment by Petr-Petrik** [comment]
> 
> 
> @lenjon might be more precise here.
> My take is that, what you say would be correct if the selection of plots was purely random. However, the Heterogeneity-Constrained Resampling (HCR) algorithm also takes into account species composition:
> 
> > For those grid cells with more than 50 vegetation plots (n = 858), we randomly selected up to 50 vegetation plots using the heterogeneity-constrained random resampling algorithm from Lengyel et al. (2011) [37]. This approach optimizes the selection of a random subset of vegetation plots that encompasses the highest variability in species composition while avoiding peculiar and rare communities, which may represent outliers. We based the quantification of variability in plant species composition among the 50 randomly selected vegetation plots by computing the mean and the variance of the Jaccard’s dissimilarity index (38) between all possible pairs of vegetation plots for a given random selection of 50 vegetation plots (n = 1225)
> 
> This means that, in case of plots with identical climatic\soil conditions from different continents, the algorithm will avoid a redundant selection of (+/- similar) plots from the same continent, but rather include as much diversity as possible, i.e., plot from all continents represented, as long as the species composition is sufficiently dissimilar.

I would avoid using the term "peculiar community" as this is subjective.
