### ISSUE TITLE
Acknowledgments

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#6]
A starting point for the acknowledgements could be [Bruelheide et al. 2019](https://onlinelibrary.wiley.com/doi/10.1111/jvs.12710). But we'll need to update them. How could we do that without too much manual editing?

**Comment by hbruelheide** [comment]
I would simply copy the acknowledgements from Bruelheide et al. 2019, but only include the co-authors that contributed data. The others would have to opt-in, and only then, would become the chance to also add something to the acknowledgements.

**Comment by fmsabatini** [comment]
Done. Need to be double checked by coauthors, and might complemented in case of new authors joining in
