### ISSUE TITLE
Gap-Filling - More explanation needed

### ISSUE THREAD

**Issue by fmsabatini** [fmsabatini/sPlotOpen_Manuscript#71]
https://github.com/fmsabatini/sPlotOpen_Manuscript/pull/69
@luiscayuela suggested:
*I think it would be desirable to explain a little bit further how missing values were interpolated. Was this done using trait values from phylogenetic-closely related species? What kind of assumptions this kind of approach imply (e.g. trait conservatism if a phylogenetic approach was used or environmental filtering if a plot-based approach was used)?*

maybe @fisw10 could help here?

**Comment by fisw10** [comment]
Good suggestion! The interpolation was done across all species present in TRY and sPlot. As such, we didn't filter by phylogeny nor plot. One assumption common across all gap-filling approaches is that the data is missing completely at random. Although there will likely be some bias in our dataset (e.g. common vs rare species), the effects should be minimal. Otherwise, there are no a priory assumptions. As this is a Bayesian machine learning approach, the algorithm "learns" from the data. I.e. if there was a phylogenetic signal in the data, this was used to fill the gaps but where no such signal was apparent, none was introduced.

**Comment by fmsabatini** [comment]
> wiser-susan commented 8 hours ago in PR https://github.com/fmsabatini/sPlotOpen_Manuscript/pull/129

>I am very concerned about applying the gap-filling method to assign traits from TRY to New Zealand species. Given our high rate of endemism -- 80% of the flora -- what are the implications of using this approach? It's not as if trait values may even exist for closely related taxa. I found the cited papers for the method quite dense and it will take me a lot of effort to get my head around this method. But I would be worried if there is some kind of bias in the trait values and then naive users of the dataset will just accept them and come up with wonky predictions and conclusions for our part of the globe.
I have encountered a different sort of problem when NZ species occurrence data were intersected with a global database of bark thickness. In this example, they only retained species that were represented in the database and these were all introduced to NZ (northern hemisphere conifers). This led to the completely wrong conclusion that NZ is dominated by thick-barked trees which would imply fire adaptation, whereas the opposite is true. I assume the gap-filling technique is meant to overcome this. I think there needs to be a bit more description provided here about how this gap filling works and what the limitations might be. Alternatively, it could be useful to present a table of countries and the % of the species that required gap filling to derive traits.

**Comment by fmsabatini** [comment]
I integrated the points raised by @fisw10 in the text, and clarified that, for those species where no trait-observation was available, no gap-filling was run. This should answer to @wiser-susan's comment. Endemic species without any trait information, were simply left as NA. When calculating CWM, we report the proportion of completeness (i.e., the proportion of species in each plot, for which we had (gap-filled) trait information). If these values are low, then the use of CWM is not recommended.

These changes are here:
https://github.com/fmsabatini/sPlotOpen_Manuscript/blame/master/content/30.Methods.md#L58
