### ISSUE TITLE
General comments on Manubot...

### ISSUE THREAD

**Issue by kamapu** [fmsabatini/sPlotOpen_Manuscript#74]
Although this is out of topic but I like to leave some impressions about Manubot here. I was looking for an option similar to Google Docs but working with markdown documents instead of the "Office" versions at Google. Manubot seem to be a good one but I have some concerns regarding the complexity, especially for people that are not used to work with markdown or R-markdown and Versioning Control Systems (Git in this case).

Here what I miss:

- A more encapsulated way to handle editions/suggestions. i.e. the editor could go direct to the view of the manuscript and do edits.
- A live display of editions/suggestions on the view of the document.
- A possibility to do in-line comments.

I know, this is rather a message for developers but for users but maybe the next time it is better to write a sort of "Go-Straight-Instructions".

**Comment by fmsabatini** [comment]
Thanks @kamapu. I will link your suggestions to the issue page of the Manubot project
Issue: https://github.com/manubot/rootstock/issues/339
